### ISSUE TITLE
todo 

### ISSUE THREAD

**Issue by bstiq** [Bastardkb/splinktegrated#1]
- [x] use usb-c C963373 
- [x] remove reset buttons, all of them... leave 4 pads exposed
- [x] move 3.3V voltage regulator so it doesn't clash with the USB
- [x] route 3.3v to serial port (instead of 5v)
- [x] route 3.3v to rgb and trackball
- [x] make left/right easier to differentiate: jumper, reset button, usb-c
- [x] flip jumper

**Comment by bstiq** [comment]
fixed as of 1.1
